apiVersion: v1
kind: Secret
metadata:
  namespace: kubeflow
  name: app-secret
type: Opaque
data:
  # base64 encoded
  backend-service: aHR0cDovLzEyNy4wLjAuMTo1NTAwCg== # http://127.0.0.1:5500
  frontend-service: aHR0cDovLzEyNy4wLjAuMTozMDAw # http://127.0.0.1:3000
  ml-service: aHR0cDovLzEyNy4wLjAuMTo0MDAw # http://127.0.0.1:4000